# Generated by Django 4.0.4 on 2022-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
