# Generated by Django 4.0.4 on 2022-06-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
