# Generated by Django 4.0.4 on 2022-06-08 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_departments_created_by'),
        ('accounts', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.BooleanField()),
                ('created_by', models.CharField(default='admin', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone phone number', regex='^\\+?1?\\d{10,10}$')])),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departments')),
            ],
        ),
    ]
