# Generated by Django 4.0.4 on 2022-06-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userwithrequestid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWithRequestId',
        ),
    ]
